repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.378
  hooks:
    - id: pyright
      additional_dependencies: []
      env:
        PYRIGHT_PYTHON_GLOBAL: /Users/latkins/git/jax_diffusion/.venv/bin/python3